add/drop track for user feature, working on ex handler
avvinidiktov/capitalOneApp pull request #2
Opened 2020-11-12 09:26 UTC by avvinidiktov

2020-11-12 14:20 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/Configuration/WebSecurityConfig.java
> +                .hasRole(Role.USER.name())
user role for admin scope

2020-11-12 14:21 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/DTO/AuthResponce.java
>  public class AuthResponce {
Response

2020-11-12 14:21 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/DTO/CompanyInfoDTO.java
> +public class CompanyInfoDTO {
Do we need an empty class

2020-11-12 14:23 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/Entity/CompanyTrack.java
> +        this.active = false;
do not good idea to use a logic in an Entity class. Entity has to be POJO

2020-11-12 14:25 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/Entity/User.java
> +import lombok.*;
please do not use imports with an asterisk. Could you please a number of imports in your IDE

2020-11-12 14:26 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/Entity/User.java
> +@Getter
Why do remove '@Data'? You can use '@Data" with  '@AllArgsConstructor'

2020-11-12 14:27 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/Entity/User.java
> +    }
the same additional logic

2020-11-12 14:44 UTC, AlRezz requested changes
Check comments

2020-11-12 14:47 UTC, AlRezz commented on src/main/java/com/gmail/avvinidiktov/capitalOne/Configuration/WebSecurityConfig.java
>                  .antMatchers("/api/auth/**")
Could you please add a 'Home' page for any user

2020-11-13 09:54 UTC, avvinidiktov commented on src/main/java/com/gmail/avvinidiktov/capitalOne/DTO/CompanyInfoDTO.java
> +public class CompanyInfoDTO {
forget to unchek file in commit menu

2020-11-18 11:46 UTC, avvinidiktov commented
now for each lvl of sub we have static num of tracks

2020-11-26 14:03 UTC, AlRezz approved these changes

2020-11-28 14:12 UTC, merged